package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"mime/multipart"
	"net/http"
	"time"
)

func main() {
	fmt.Println("=== INITIALIZING DATA ===")
	// Get tokens from Dummy accounts generated by backend initDB
	userToken := login("user", "user123")
	adminToken := login("admin", "admin123")
	tech1Token := login("tech", "tech123") // Tech Support 1 (created automatically by initDB)

	// Create a second Tech Support
	createUser(adminToken, "Tech Dua", "tech2", "tech2_123", "Tech", "0")
	tech2Token := login("tech2", "tech2_123") // Tech Support 2
	
	// Create a User Ticket
	createTicket(userToken, "PC Meledak", "Tiba tiba bau hangus", "Troubleshoot")
	
	// Admin assign to Tech 1
	var ticketID string
	tickets := getTickets(adminToken)
	if len(tickets) > 0 {
		ticketID = tickets[0]["id"].(string)
	}
	
	// Find tech1 ID
	techs := getUsers(adminToken)
	var tech1ID string
	for _, u := range techs {
		if u["username"] == "tech" {
			tech1ID = u["id"].(string)
		}
	}
	
	// Admin assignments
	updateTicket(adminToken, ticketID, "tech_id", tech1ID)
	
	fmt.Println("=== CHECKING VISIBILITY ===")
	time.Sleep(1 * time.Second)

	// Tech 1 Should See the Ticket
	t1 := getTickets(tech1Token)
	fmt.Printf("Tech 1 (Assignee) melihat %d tiket.\n", len(t1))
	if len(t1) > 0 {
		fmt.Printf("   > ID Tiket: %v\n", t1[0]["id"])
	}

	// Tech 2 Should NOT see the ticket
	t2 := getTickets(tech2Token)
	fmt.Printf("Tech 2 (Bukan Assignee) melihat %d tiket.\n", len(t2))
}

func login(user, pass string) string {
	b, _ := json.Marshal(map[string]string{"username": user, "password": pass})
	req, _ := http.NewRequest("POST", "http://localhost:8080/api/login", bytes.NewBuffer(b))
	req.Header.Set("Content-Type", "application/json")
	resp, _ := http.DefaultClient.Do(req)
	var res map[string]interface{}
	json.NewDecoder(resp.Body).Decode(&res)
	if res["token"] == nil {
		fmt.Println("FAILED LOGIN:", user)
		return ""
	}
	return res["token"].(string)
}

func createUser(token, name, user, pass, role, phone string) {
	b, _ := json.Marshal(map[string]string{"name": name, "username": user, "password": pass, "role": role, "phone": phone})
	req, _ := http.NewRequest("POST", "http://localhost:8080/api/users", bytes.NewBuffer(b))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+token)
	http.DefaultClient.Do(req)
}

func createTicket(token, title, desc, typ string) {
	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	writer.WriteField("title", title)
	writer.WriteField("description", desc)
	writer.WriteField("type", typ)
	writer.Close()

	req, _ := http.NewRequest("POST", "http://localhost:8080/api/tickets", body)
	req.Header.Set("Content-Type", writer.FormDataContentType())
	req.Header.Set("Authorization", "Bearer "+token)
	http.DefaultClient.Do(req)
	time.Sleep(500 * time.Millisecond) // await DB
}

func getTickets(token string) []map[string]interface{} {
	req, _ := http.NewRequest("GET", "http://localhost:8080/api/tickets", nil)
	req.Header.Set("Authorization", "Bearer "+token)
	resp, _ := http.DefaultClient.Do(req)
	var res []map[string]interface{}
	json.NewDecoder(resp.Body).Decode(&res)
	return res
}

func getUsers(token string) []map[string]interface{} {
	req, _ := http.NewRequest("GET", "http://localhost:8080/api/users", nil)
	req.Header.Set("Authorization", "Bearer "+token)
	resp, _ := http.DefaultClient.Do(req)
	var res []map[string]interface{}
	json.NewDecoder(resp.Body).Decode(&res)
	return res
}

func updateTicket(token, id, field, val string) {
	payload := map[string]string{"id": id}
	payload[field] = val
	b, _ := json.Marshal(payload)
	req, _ := http.NewRequest("PUT", "http://localhost:8080/api/tickets", bytes.NewBuffer(b))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+token)
	http.DefaultClient.Do(req)
}
